[[getting-started]]
== Getting started ==
How to activate Chaos Monkey for Spring Boot in your existing Spring Boot App?

There are two ways to integrate the Chaos Monkey for Spring Boot into your existing Spring Boot app. Either it is an integral part of your project and is listed in the POM or you can include it as an external dependency when starting your Spring Boot App.

=== Dependency in your POM file ===

1.) Let´s activate Chaos Monkey for Spring Boot, only 2 steps are required

[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>chaos-monkey-spring-boot</artifactId>
    <version>{project-version}</version>
</dependency>
----

2.) Start your Spring Boot App Command-Line example:

[source,txt,subs="verbatim,attributes"]
.command-line
----
# spring profile
java -jar your-app.jar --spring.profiles.active=chaos-monkey

# system property
java -jar your-app.jar -DLOAD_CHAOS_MONKEY=true
----
=== External dependency JAR file
You can extend your existing application with the CM4SB and add it as an external dependency at startup. For this it is necessary to use the PropertiesLauncher of Spring Boot.

You can specify the necessary properties to activate the CM4SB as an external property file using the parameter *--spring.config.location*.

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files[Spring Boot external config documentation]

This special JAR file is also available via Maven:
[source,xml,subs="verbatim,attributes"]
.pom.xml
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>chaos-monkey-spring-boot</artifactId>
    <classifier>jar-with-dependencies</classifier>
    <version>{project-version}</version>
</dependency>
----
Start your Spring Boot application, add Chaos Monkey for Spring Boot JAR and properties.
[source,txt,subs="verbatim,attributes"]
.command-line
----
java -cp your-app.jar
    -Dloader.path=chaos-monkey-spring-boot-{project-version}-jar-with-dependencies.jar
        org.springframework.boot.loader.PropertiesLauncher
    --spring.profiles.active=chaos-monkey
    --spring.config.location=file:./chaos-monkey.properties
----

CAUTION: Each Chaos Monkey version is built for a specific Spring Boot version, which can be found on the https://github.com/codecentric/chaos-monkey-spring-boot/releases[release page]. If you're using a different Spring Boot version in your application, Chaos Monkey might break when it is added as external jar.

It is your decision how you want to integrate and use the CM4SB. There is no difference between the two possibilities.

=== Minimal CM4SB configuration via property file
In this example, we want to make latency attacks on our *@Service* annotated classes.

[source,txt,subs="verbatim,attributes"]
.application.properties:
----
spring.profiles.active=chaos-monkey
chaos.monkey.enabled=true

chaos.monkey.watcher.service=true
chaos.monkey.assaults.latencyActive=true
----
[source,yml,subs="verbatim,attributes"]
.application.yml:
----
spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      service: true
    assaults:
      latencyActive: true
----

Configuration via property file offers all available options, but requires a restart to apply changes. To avoid this, you can configure it via Actuator.