[[getting-started]]
== Getting started ==
There are two ways to activate Chaos Monkey for Spring Boot (CM4SB) in your existing Spring Boot app. Either by adding it to your regular app dependencies (eg. `pom.xml/build.gradle(.kts)`) or instead, you include it as an external dependency when starting your Spring Boot app.

=== Adding Chaos Monkey for Spring Boot ===
[#_as_dependency]
==== As dependency

1.) Add Chaos Monkey for Spring Boot as dependency for your project

[source,xml,indent=0,subs="verbatim,attributes",role="primary"]
.Maven
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>chaos-monkey-spring-boot</artifactId>
    <version>{project-version}</version>
</dependency>
----

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Gradle
----
implementation 'de.codecentric:chaos-monkey-spring-boot:{project-version}'
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Gradle Kotlin
----
implementation("de.codecentric:chaos-monkey-spring-boot:{project-version}")
----

NOTE: If you want to use the latest snapshot version, add the sonatype staging repository `https://oss.sonatype.org/content/repositories/snapshots/`

2.) Start your Spring Boot App with the `chaos-monkey` spring profile enabled. We also pass some properties to assault services with latency.

Command line example:

[source,txt,subs="verbatim,attributes",role="primary"]
.Spring profile
----
java -jar your-app.jar --spring.profiles.active=chaos-monkey --chaos.monkey.enabled=true --chaos.monkey.watcher.service=true --chaos.monkey.assaults.latencyActive=true
----

[source,txt,subs="verbatim,attributes",role="secondary"]
.System property (alternative)
----
java -jar your-app.jar -DLOAD_CHAOS_MONKEY=true --chaos.monkey.enabled=true --chaos.monkey.watcher.service=true --chaos.monkey.assaults.latencyActive=true
----


Passing all arguments through command line is a bit cumbersome, but you can also specify the properties in your application.properties file, head over to <<_minimal_cm4sb_configuration_via_property_file>> to find out how.

==== Using external dependency jar file
If you dont want to add Chaos Monkey for Spring Boot to your dependencies (see <<_as_dependency>>), you can use the external jar solution as an alternative.

You can extend your existing application with the CM4SB and add it as an external dependency at startup.For this it is necessary to use the PropertiesLauncher of Spring Boot.

You can specify the necessary properties to activate the CM4SB as an external property file using the parameter *--spring.config.location*.

https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files[Spring Boot external config documentation]

This special JAR file is also available through Maven Central:
[source,xml,subs="verbatim,attributes",role="primary"]
.Maven
----
<dependency>
    <groupId>de.codecentric</groupId>
    <artifactId>chaos-monkey-spring-boot</artifactId>
    <classifier>jar-with-dependencies</classifier>
    <version>{project-version}</version>
</dependency>
----

[source,groovy,indent=0,subs="verbatim,attributes",role="secondary"]
.Gradle
----
implementation 'de.codecentric:chaos-monkey-spring-boot:{project-version}:jar-with-dependencies'
----

[source,kotlin,indent=0,subs="verbatim,attributes",role="secondary"]
.Gradle Kotlin
----
implementation("de.codecentric:chaos-monkey-spring-boot:{project-version}:jar-with-dependencies")
----

Start your Spring Boot application, add Chaos Monkey for Spring Boot JAR and properties.
[source,txt,subs="verbatim,attributes"]
.command-line
----
java -cp your-app.jar
    -Dloader.path=chaos-monkey-spring-boot-{project-version}-jar-with-dependencies.jar
        org.springframework.boot.loader.PropertiesLauncher
    --spring.profiles.active=chaos-monkey
    --spring.config.location=file:./chaos-monkey.properties
----

CAUTION: Each Chaos Monkey version is built for a specific Spring Boot version, which can be found on the https://github.com/codecentric/chaos-monkey-spring-boot/releases[release page]. Chaos Monkey might break when it is added as external jar and you're using a different Spring Boot version in your application.

It is your decision how you want to integrate and use the CM4SB. There is no difference between the two possibilities. However, it's easier to add it as a dependency (see <<_as_dependency>>), so you don't need to adjust the starting of your application.

[#_minimal_cm4sb_configuration_via_property_file]
=== Minimal CM4SB configuration via property file
In this example, we want to make latency attacks on our `*@Service*` annotated classes.

[source,txt,subs="verbatim,attributes",role="primary"]
.application.properties:
----
spring.profiles.active=chaos-monkey
chaos.monkey.enabled=true

chaos.monkey.watcher.service=true
chaos.monkey.assaults.latencyActive=true
----
[source,yaml,subs="verbatim,attributes",role="secondary"]
.application.yml:
----
spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      service: true
    assaults:
      latencyActive: true
----

Configuration via property file offers all available options, but requires a restart to apply changes. To avoid this, you can configure it via Actuator.