[[watchers]]
== Watcher ==
A watcher is a Chaos Monkey for Spring Boot component, that will scan your app for a specific type of annotation.

Following Spring annotation are supported:

- @Controller
- @RestController
- @Service
- @Repository
- @Component

With the help of https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-api[Spring AOP], Chaos Monkey recognizes the
execution of a _public_ method and will either not execute any action or start one of its assaults. You can customize the behave by
<<configuration,configuration>>.

Next to the _Spring_ stereotype _AOP_ watchers, Chaos Monkey can also watch the

* https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.auto-configured-health-indicators[Spring Boot HealthIndicators]

and assault the health checks with exceptions and latency. Exceptions will let the _HealthIndicators_ go into status _DOWN_ and the latency assault postpone the response.

Besides the _AOP_ based watchers, Chaos Monkey for Spring Boot also provides watchers for:

- RestTemplate
- WebClient

The watchers will inject exception and latency based assaults for all _RestTemplate_ and _WebClient_ beans in the Spring Context based on the given assault configuration.

[IMPORTANT]
====
_RestTemplates_ and _WebClients_ which are created not as a bean via _new RestTemplate()_ and _WebClient.create()_ are not getting instrumented.
====

=== Customize Watcher
You can customize the behavior of all watchers using the property *watchedCustomServices* and decide which classes and public methods
should be attacked. You can set the property to reference public methods, classes or packages.

If `watchedCustomServices` is not set, all classes and public methods recognized by the enabled watchers are attacked.

You can either maintain the list in your application properties or adjust it at runtime using the Spring Boot Actuator Endpoint.

See following examples:
[source,json,subs="verbatim,attributes"]
.Chaos Monkey Spring Boot Actuator Endpoint (/actuator/chaosmonkey/assaults)
----
{
  "level": 3,
  "latencyActive": true,
  "latencyRangeStart": 1000,
  "latencyRangeEnd": 3000,
  "watchedCustomServices": [
    "com.example.chaos.monkey.chaosdemo.controller.HelloController.sayHello",
    "com.example.chaos.monkey.chaosdemo.service.HelloService"
  ]
}
----


[source,txt,subs="verbatim,attributes",role="primary"]
.application.properties:
----
chaos.monkey.enabled=true
chaos.monkey.watcher.controller=true
chaos.monkey.assaults.level=1
chaos.monkey.assaults.latency-active=true
chaos.monkey.assaults.watchedCustomServices=com.example.chaos.monkey.chaosdemo.controller.HelloController.sayHello,com.example.chaos.monkey.chaosdemo.service.HelloService
----

[source,yaml,subs="verbatim,attributes",role="secondary"]
.application.yml:
----
chaos:
  monkey:
    enabled: true
    watcher:
      controller: true
    assaults:
      level: 1
      latency-active: true
      watched-custom-services:
        - com.example.chaos.monkey.chaosdemo.controller.HelloController.sayHello
        - com.example.chaos.monkey.chaosdemo.service.HelloService
----


NOTE: This list only **restricts** the attacked classes found by watchers. If a class or method wasn't attacked when this list was unset, it won't be attacked if it is added to the list.