# Taken from https://www.gitpod.io/docs/introduction/languages/java
FROM gitpod/workspace-full:latest

USER gitpod

RUN bash -c ". /home/gitpod/.sdkman/bin/sdkman-init.sh && \
    sdk install java && \
    sdk default java"